### ISSUE TITLE
群发接口返回结果新增字段

### ISSUE THREAD

**Issue by magicshui** [chanxuehong/wechat#140]
群发接口的返回结果，由于msg_id并不是群发统计的事件ID，所以微信新增了一个msg_data_id的字段：

http://mp.weixin.qq.com/wiki/15/5380a4e6f02f2ffdc7981a8ed7a40753.html#.E6.A0.B9.E6.8D.AE.E5.88.86.E7.BB.84.E8.BF.9B.E8.A1.8C.E7.BE.A4.E5.8F.91.E3.80.90.E8.AE.A2.E9.98.85.E5.8F.B7.E4.B8.8E.E6.9C.8D.E5.8A.A1.E5.8F.B7.E8.AE.A4.E8.AF.81.E5.90.8E.E5.9D.87.E5.8F.AF.E7.94.A8.E3.80.91

![image](https://cloud.githubusercontent.com/assets/330987/9216566/dc33493c-40ed-11e5-8181-9ffc96d2f4e9.png)

**Comment by chanxuehong** [comment]
谢谢  更新了
