### ISSUE TITLE
wechat 的  log 怎么给你们一个好的接口，或者说你们需要一个什么样的接口 

### ISSUE THREAD

**Issue by chanxuehong** [chanxuehong/wechat#151]
感觉现在的log设计的不够合理，你们都提提意见，说说怎么处理的比较好

**Comment by rainsight** [comment]
你好，wechat提供的日志确实太少，不便于调试。建议使用github.com/Sirupsen/logrus包，非常灵活，功能也很强大，已经被很多知名开源项目（如Docker）所采用。

**Comment by rainsight** [comment]
你好，我们的项目目前正在使用你的wechat包。wechat提供的日志确实太少，不便于调试。建议使用github.com/Sirupsen/logrus包，非常灵活，功能也很强大，已经被很多知名开源项目（如Docker）所采用。我目前正在往相关AccessTokenServer和TicketServer里加相关log，以便调试。希望能合并到你的项目里。:)
