### ISSUE TITLE
signature is empty

### ISSUE THREAD

**Issue by fmzquant** [chanxuehong/wechat#159]
偶尔会出现这个消息 signature is empty, 然后微信提示 "该公众号暂无法提供服务, 请稍后重试"  我再发一遍, 服务器就收到正常消息了, AES加密的, 就好了, 没机会重现，这个是什么原因??

**Comment by chanxuehong** [comment]
这个应该是 腾讯发给你服务器的时候  没有带上signature
能出现这个情况的场景就是验证回调url的时候和明文模式给回调url发送消息的时候，没有带上signature

在加密模式情况下，发送消息不会出现这个错误，你可以看看代码，所以我认为这是腾讯的问题，你可以查看下你的log，我记得我也遇到过这样的问题，应该是腾讯的问题

谢谢你的反馈

**Comment by fmzquant** [comment]
嗯，多谢了，你这个很好用, 几分钟就整合到系统里了, 支持你, 有问题随时反馈.
