### ISSUE TITLE
security  包不存包

### ISSUE THREAD

**Issue by kekek** [chanxuehong/wechat#161]
/Web/go/src/github.com/chanxuehong/wechat/mp/serve_http.go:21:2: cannot find package "github.com/chanxuehong/util/security" in any of:
    /usr/local/Cellar/go/1.5.1/libexec/src/github.com/chanxuehong/util/security (from $GOROOT)
    /Web/go/src/github.com/chanxuehong/util/security (from $GOPATH)

项目中有多处使用该包

**Comment by forrestsun** [comment]
同问如何解决？

**Comment by forrestsun** [comment]
好吧，发现了，在另一个包里

**Comment by leohgbs** [comment]
https://github.com/chanxuehong/util
