### ISSUE TITLE
调查

### ISSUE THREAD

**Issue by chanxuehong** [chanxuehong/wechat#167]
如果我想定义一个类型，然后所有的到腾讯接口的访问都经过这个类型，就是
https://github.com/chanxuehong/wechat/blob/master/mp/shakearound/account/account.go#L45
这里的 mp.Client

那么你认为这个类型的名称叫什么好？
APIProxy
ApiProxy
ApiAdapter
Proxy
Delegate
Requester
Client
还是有其他的，请留下你的答案

**Comment by ruooooooli** [comment]
HttpProxy
RequestProxy

**Comment by chanxuehong** [comment]
@ruooooooli 
这个 RequestProxy 我原来考虑过
我考虑的是 Requester

**Comment by ruooooooli** [comment]
@chanxuehong 
Request 或者 Requester 我感觉都可以

**Comment by transtone** [comment]
Requester

**Comment by andeya** [comment]
Requester

**Comment by chanxuehong** [comment]
但是我觉得 ApiProxy 蛮好，咋办 哈哈

**Comment by HermitCarb** [comment]
Requester然后加个自己喜欢的前缀

**Comment by ysqi** [comment]
Gateway

**Comment by yh453926638** [comment]
ApiProxy

**Comment by chanxuehong** [comment]
ApiAdapter 咋样
