### ISSUE TITLE
希望能保留master分支

### ISSUE THREAD

**Issue by tossp** [chanxuehong/wechat#169]
好几个项目使用了持续构建
用`go get -v -x`命令安装依赖，现在报错如下

```
git clone https://github.com/chanxuehong/wechat /go/src/github.com/chanxuehong/wechat
cd /go/src/github.com/chanxuehong/wechat
git show-ref
cd /go/src/github.com/chanxuehong/wechat
git checkout master
# cd /go/src/github.com/chanxuehong/wechat; git checkout master
error: pathspec 'master' did not match any file(s) known to git.
package github.com/chanxuehong/wechat/mp: exit status 1
github.com/gorilla/websocket (download)
```

**Comment by chanxuehong** [comment]
好

**Comment by tossp** [comment]
谢谢

_有任何疑问或者建议，请及时联系！ 谢谢！_

_砼砼.朱浩 ————————————————————————————联系电话: +86-13419290962腾讯QQ:156888120
http://sighttp.qq.com/authd?IDKEY=c31473151092df4e0b8b865644d797cb27595df05699a32e
个人主页: http://TossP.com
http://tossp.com/_

_成都晨云信息技术有限责任公司公司座机: +86-028-81700511工作手机: +86-13419290962腾讯QQ:156888120
http://sighttp.qq.com/authd?IDKEY=c31473151092df4e0b8b865644d797cb27595df05699a32e
公司主页: http://www.CdMcit.Com
http://www.cdmcit.com/公司地址:__四川省成都市光华东三路中铁西城写字楼5栋802_

2016-01-14 12:06 GMT+08:00 chanxuehong notifications@github.com:
