### ISSUE TITLE
支持 http://gopkg.in/ 的版本控制方法

### ISSUE THREAD

**Issue by magicshui** [chanxuehong/wechat#185]
产先生，目前 v2 是最新的版本？但是当我们在go get 的时候，发现会出现依赖的错误，是否可以支持gopkg.in 的版本控制方法？

**Comment by chanxuehong** [comment]
你们系统不是一直在master吗，直接go get 也会出错？
gopkg 回头我研究研究 没有弄过

**Comment by magicshui** [comment]
看到项目中已经加入了版本号但是 go get gopkg.in/chanxuehong.v1 或者 v2 都错误
因为 subpackage 引入的有根目录的路径

**Comment by chanxuehong** [comment]
哦  懂你的意思了  那我这么一改  对以前的代码貌似也会不兼容啊

**Comment by magicshui** [comment]
是的，这个是一个比较艰难的事情，你可以先关了；
另外就是目前各个分支以后不会有大的变化了吧？如果目前在用的分支以后不会出现被删除等状况也是可以接受的：）

**Comment by chanxuehong** [comment]
v1 肯定是不会变的了  
当然 v2 肯定是会增加功能
master 某一天会切换到 v2 上去

PS:
你们原来的代码应该都是基于v1的吧，那就一直v1好了，除了bug我不会动的了

**Comment by chanxuehong** [comment]
不过如果像你那么改的话  可以同时使用v1  和 v2  了 
就是老的代码引入路径要改下

**Comment by chanxuehong** [comment]
还有一个问题  要是 gopkg.in 倒闭了咋办？
