### ISSUE TITLE
v2版微信支信相关的请求地址都是错的。

### ISSUE THREAD

**Issue by dearchun** [chanxuehong/wechat#191]
func MicroPay(clt *core.Client, req map[string]string) (resp map[string]string, err error) {
    return clt.PostXML("https://api.core.weixin.qq.com/pay/micropay", req)
}
正确的不是https://api.mch.weixin.qq.com/pay/micropay吗？
好象所有的mch被批量替换成了core了。

**Comment by chanxuehong** [comment]
好的  谢谢提醒  我上次重构替换的
