### ISSUE TITLE
测试友好

### ISSUE THREAD

**Issue by ericx10ng** [chanxuehong/wechat#196]
现在在搞支付，要用到pay相关部份，现在的代码不太方便测试，发请求都用了具体类型core.Client，而且url也写死在代码里, 没办法mock一个，如果是接口就好，总不能测试就去请求微信那边吧

**Comment by chanxuehong** [comment]
不好意思，现在比较忙，才看到你这个！

对于你的建议, 如果 client 用接口代替也不能解决问题,  其实那些方法也是 client 的 PostXML 的一个简单封装, 如果你想弄两套环境, 可以直接用 Client.PostXML 的方法, 不要用 wrapper 方法
