### ISSUE TITLE
client不能指定access_token

### ISSUE THREAD

**Issue by magicshui** [chanxuehong/wechat#2]
我已经获取了access_token并保存在数据库中，但是当我想建立新的Client实例的时候，只能通过：
NewClient 和 NewClientEx 来创建，但是我别的程序不知道这个appid和secret是多少，而使用Ex有需要构建一个tokenCache的类，能不能暴露一个新的函数：
NewClientFromToken(accessToken string)的方式，传入accessToken就直接创建？

**Comment by chanxuehong** [comment]
构建一个 TokenCache 很麻烦么，你都能得到 accessToken 了

``` golang
type MyTokenCache string

func (tc MyTokenCache) Token() (token string, err error) {
    token = string(tc)
    return
}

var _ client.TokenCache = MyTokenCache("")
```

现在用  NewClientEx 创建，和你要求的那个函数有多少区别呢？？？

``` golang
NewClientEx(MyTokenCache("access_token"), nil, nil)
```

**Comment by magicshui** [comment]
谢谢：）
