### ISSUE TITLE
判断微信版本号有bug

### ISSUE THREAD

**Issue by haoyue0603** [chanxuehong/wechat#201]
util.WXVersion()

不是有效的微信浏览器 user-agent, Mozilla/5.0 (Linux; Android 4.4.4; Che1-CL10 Build/Che1-CL10; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/53.0.2785.49 Mobile MQQBrowser/6.2 TBS/043128 Safari/537.36 MicroMessenger/6.5.7.1041 NetType/WIFI Language/zh_CN

**Comment by chanxuehong** [comment]
谢谢 已经修复
