### ISSUE TITLE
ExchangeToken() dial tcp: i/o timeout

### ISSUE THREAD

**Issue by fireice009** [chanxuehong/wechat#202]
在 chrome 中访问 `https://api.weixin.qq.com/sns/oauth2/access_token?appid=xxx&secret=xxx&code=xxx&grant_type=authorization_code` 正常。
但在代码里面调用 `token, xerr := oauth2Client.ExchangeToken(code)` 得到 xerr: 
`Get https://api.weixin.qq.com/sns/oauth2/access_token?appid=xxx&secret=xxx&code=xxx&grant_type=authorization_code: dial tcp: i/o timeout`

以下命令也超时
`curl -sL https://api.weixin.qq.com/sns/oauth2/access_token?appid=xxx&secret=xxx&code=xxx&grant_type=authorization_code`

OS: macOS Sierra 10.12.3 (16D30)

**Comment by chanxuehong** [comment]
请问还有问题吗

**Comment by chanxuehong** [comment]
这个问题我个人认为还是你当时的环境的问题吧，不然你不会 curl 也不行，而且这块我们工作的好好的

**Comment by fireice009** [comment]
系统的问题，放在线上的linux服务器跑没有问题。
