### ISSUE TITLE
go get 直接报错啊

### ISSUE THREAD

**Issue by Fengxq2014** [chanxuehong/wechat#205]
go get -u -v github.com/chanxuehong/wechat.v2        
github.com/chanxuehong/wechat.v2 (download)
package github.com/chanxuehong/wechat.v2: no buildable Go source files in /home/defned/.gvm/pkgsets/go1.8.3/global/src/github.com/chanxuehong/wechat.v2

**Comment by Barbery** [comment]
同遇到。。。请问怎么安装，难道要手动拷贝进去吗

**Comment by Barbery** [comment]
哦 原来作者是弄成分模块下载的。。。
例如我要开发授权的功能，只要下载这两个包就好了

```
go get -u -v github.com/chanxuehong/wechat.v2/oauth2
go get -u -v github.com/chanxuehong/wechat.v2/mp/oauth2
```

**Comment by chanxuehong** [comment]
go get -u github.com/chanxuehong/wechat.v2/...
