### ISSUE TITLE
为什么注释说整个系统只能存在一个 DefaultAccessTokenServer 实例？

### ISSUE THREAD

**Issue by xiaojia1001** [chanxuehong/wechat#209]
每个AccessTokenServer都只能适用于一个Corp，实际场景是一个微信应用需要服务很多企业，不太明白为什么作者在注释中反复强调整个系统只能存在一个 DefaultAccessTokenServer 实例？ 

type DefaultAccessTokenServer struct {
	corpId     string
	corpSecret string
	httpClient *http.Client

	resetTickerChan chan time.Duration // 用于重置 tokenDaemon 里的 ticker

	tokenGet struct {
		sync.Mutex
		LastTokenInfo accessTokenInfo // 最后一次成功从微信服务器获取的 access_token 信息
		LastTimestamp int64           // 最后一次成功从微信服务器获取 access_token 的时间戳
	}

	tokenCache struct {
		sync.RWMutex
		Token string
	}
}

**Comment by chanxuehong** [comment]
一个 corpId 只能有一个
