### ISSUE TITLE
请问多进程下，像access token之类的东西应该怎么处理？

### ISSUE THREAD

**Issue by lcg635** [chanxuehong/wechat#216]
现在的DefaultAccessTokenServer只支持单进程吧？

**Comment by yanjunhui** [comment]
我现在的方式是并发一个进程专门去维护access token, 存在redis
其他进程使用 都去redis去读token

**Comment by lcg635** [comment]
明白了，多谢啦

**Comment by chanxuehong** [comment]
嗯  一般都是存 redis，然后实现 AccessTokenServer 接口，去 redis 取
