### ISSUE TITLE
能否写此使用全套例子

### ISSUE THREAD

**Issue by nicle-lin** [chanxuehong/wechat#221]
* 功能看起来很强大，但不知道怎么用

**Comment by chanxuehong** [comment]
功能其实也不是很强大，主要围绕的就是一个 token 的处理。

https://github.com/chanxuehong/wechat/blob/v2/mp/README.md

这里是主要例子，所有的功能基本都是围绕这个模板来写的

**Comment by RichardWeiYang** [comment]
这个例子我看懂了，但是那个授权的例子没跑通。

最后出现的是类似 http://blog.csdn.net/u014185140/article/details/78347110 上的错误。

我理解的流程是在微信上访问http://h4629e.natappfree.cc/page1，经过验证后会跳转到http://h4629e.natappfree.cc/page1。

所以我在代码里改成了，

	oauth2RedirectURI = "http://h4629e.natappfree.cc/page2" 

在公众号测试管理的“网页授权获取用户基本信息”中填入了http://h4629e.natappfree.cc/page2。

不知道我的理解哪里有问题

**Comment by chanxuehong** [comment]
这个需要你在公众号的后台设置你的回调地址的

**Comment by RichardWeiYang** [comment]
是的

我在公众号测试管理的“网页授权获取用户基本信息”中填入了

```
http://h4629e.natappfree.cc/page2
```

报的是这个错，那我应该填写什么样的地址？

**Comment by chanxuehong** [comment]
这个填的是域名吧  如果我没有记错的话

**Comment by RichardWeiYang** [comment]
You are right，看来是我没有理解清楚了。改成域名就好了。

我现在想做这个么事儿，想把你的两个例子结合一下。
就是有人授权后，可以发一个消息给这个人。

现在相当于也拿到了openid，不知道是不是可以直接给他发一个消息？
是不是看这个mp/message/mass/mass2users 接口？

**Comment by RichardWeiYang** [comment]
我猜了一下你的代码，然后写了个这样的

```
	ats := core.NewDefaultAccessTokenServer(wxAppId, wxAppSecret, nil)
	client := core.NewClient(ats, nil)
	msg := mass2users.NewText([]string{token.OpenId, "ofQQr1ioZzc1RXOdyXlC2K6nTuH4", "ofQQr1k4OgPThKvjqn0u217KpWOY"}, "welcome")
	b, _ := json.Marshal(msg)
	res, err := mass2users.Send(client, b)
```

最后返回显示的错误是

```
errcode: 40130, errmsg: invalid openid list size, at least two openid hint: [_L2XnA0601ge25]
```

我已经添加了三个openid了，为啥还是报这个错误呢？

**Comment by chanxuehong** [comment]
授权不能发，必须关注才能发！

**Comment by RichardWeiYang** [comment]
那比如现在微信中经常收到比如说千聊的课程信息，比如信用卡刷卡的信息。
这个是怎么做的呢？
