### ISSUE TITLE
wechat pay sign error

### ISSUE THREAD

**Issue by af913337456** [chanxuehong/wechat#223]
i have checked with wechat's tool , same as my sign info , but it still return "签名错误" when i use your lib to queryOrder , is there any solutions?

**Comment by chanxuehong** [comment]
是不是 key 不正确

**Comment by af913337456** [comment]
@chanxuehong  wx's problem , when i reset apiKey on they server , it work , motherfuck

**Comment by chanxuehong** [comment]
ok
