### ISSUE TITLE
log打印的太少了，非常难于调试

### ISSUE THREAD

**Issue by baiyuxiong** [chanxuehong/wechat#72]
建议添加log信息或者记录log文件。

**Comment by chanxuehong** [comment]
不好意思，才看到。
你想要打印哪些信息呢？debug版本的那些打印不能滿足你？

**Comment by chanxuehong** [comment]
比如
https://github.com/chanxuehong/wechat/blob/master/mp/client.debug.go#L52

**Comment by baiyuxiong** [comment]
哦，默认debug是关闭的吗？我没改过配置。接口调用的时候就只有一行文字信息：token is empty.

**Comment by baiyuxiong** [comment]
建议在文档里把debug相关的内容放在示例代码里

**Comment by chanxuehong** [comment]
出現 token is empty 應該是你用的方法不對！
打開debug你編譯的時候要加上tag，如：
go build -a -tags wechatdebug 你的項目路徑

**Comment by baiyuxiong** [comment]
好的，我试试
