### ISSUE TITLE
mp/media/ 中news上传方法已经被微信删除了

### ISSUE THREAD

**Issue by magicshui** [chanxuehong/wechat#82]
参考微信素材管理功能的文档：http://mp.weixin.qq.com/wiki/5/963fc70b80dc75483a271298a76a8d59.html

当前代码中这一部分在文档中已经被移除，还没有测试老的接口是否可以使用，如果不可以使用了，老的上传news的代码需要移除了：https://github.com/chanxuehong/wechat/blob/master/mp/media/media.go#L26
新的逻辑中只有多媒体素材作为临时素材上传的描述；

可以保留老的代码，但是需要说明一下使用的时候需要注意；

**Comment by chanxuehong** [comment]
http://mp.weixin.qq.com/wiki/15/5380a4e6f02f2ffdc7981a8ed7a40753.html#.E4.B8.8A.E4.BC.A0.E5.9B.BE.E6.96.87.E6.B6.88.E6.81.AF.E7.B4.A0.E6.9D.90.E3.80.90.E8.AE.A2.E9.98.85.E5.8F.B7.E4.B8.8E.E6.9C.8D.E5.8A.A1.E5.8F.B7.E8.AE.A4.E8.AF.81.E5.90.8E.E5.9D.87.E5.8F.AF.E7.94.A8.E3.80.91
