### ISSUE TITLE
素材管理视频下载和其他不同

### ISSUE THREAD

**Issue by magicshui** [chanxuehong/wechat#84]
参考：http://mp.weixin.qq.com/wiki/4/b3546879f07623cb30df9ca0e420a5d0.html
如果对于material中的DownloadMaterial()，如果类型是video，会返回的是一个json，其中包含一个下载的url，而不是多媒体文件；
需要增加一个struct来定义，另外如果能在把视频的下载也写到DownloadMaterial就最好了

**Comment by chanxuehong** [comment]
resolved
