### ISSUE TITLE
客服接口添加发送卡券的功能

### ISSUE THREAD

**Issue by magicshui** [chanxuehong/wechat#86]
见微信的文档：
http://mp.weixin.qq.com/wiki/1/70a29afed17f56d537c833f89be979c9.html#.E5.AE.A2.E6.9C.8D.E6.8E.A5.E5.8F.A3-.E5.8F.91.E6.B6.88.E6.81.AF

他的文档内容：
![image](https://cloud.githubusercontent.com/assets/330987/7764075/6e69447a-007d-11e5-89e4-796a9cd99008.png)

比较奇怪的是这个没有msgtype的属性？然后文档样式也不对，估计是文档写漏了这个字段；

**Comment by chanxuehong** [comment]
那我咋搞？我也不是腾讯啊

**Comment by magicshui** [comment]
我问下微信的人…

**Comment by chanxuehong** [comment]
结果如何
