### ISSUE TITLE
POI 接口中photo_list更新

### ISSUE THREAD

**Issue by magicshui** [chanxuehong/wechat#88]
微信把poi中的图片列表更新了，最新的格式：

```
"photo_list":[{"photo_url":"https:// XXX.com"}，{"photo_url":"https://
XXX.com"}], 
```

参加[【微信卡券】](http://mp.weixin.qq.com/wiki/9/4f455120b50741db79b54fde8896b489.html)中的文档：https://mp.weixin.qq.com/zh_CN/htmledition/comm_htmledition/res/cardticket/wx_card_document.zip

**Comment by chanxuehong** [comment]
嗯 变化了 谢谢 搞定了
