### ISSUE TITLE
抓到微信程序员一枚，反馈微信接口中的问题

### ISSUE THREAD

**Issue by magicshui** [chanxuehong/wechat#90]
R.T，打算搜集一下写SDK中微信接口的问题，一块儿写邮件发给他们，求产线生吐槽

**Comment by chanxuehong** [comment]
haha , 那好，我就两点
1、文档及时更新
2、json 标准化，就是该是整数的时候就不要加双引号，是字符串的时候加双引号

**Comment by magicshui** [comment]
已经反馈，然并卵；

**Comment by magicshui** [comment]
更新日志已经有了：
http://mp.weixin.qq.com/wiki/16/992df48524118c3e89945856694b30cc.html

**Comment by chanxuehong** [comment]
嗯 看到了
