### ISSUE TITLE
消息排重算法收集

### ISSUE THREAD

**Issue by chanxuehong** [chanxuehong/wechat#98]
因为微信推送过来的消息如果你5秒内没有处理完毕，会尝试再推送过来一个，总的三次

那么现实中，很有可能因为某些原因（逻辑处理不对在5秒内没有处理完成，或者异常）造成重发消息，
那么有什么好的算法能快速排重呢

集思广益，tks

**Comment by gaowenbin** [comment]
布隆应该可以吧
