### ISSUE TITLE
获取用户信息接口更新

### ISSUE THREAD

**Issue by magicshui** [chanxuehong/wechat#99]
微信更新了两个内容：
1. 获取单个用户信息的返回字段中增加了groupid
2. 增加了批量获取用户信息的接口

详见：http://mp.weixin.qq.com/wiki/14/bb5031008f1494a59c6f71fa0f319c66.html

**Comment by chanxuehong** [comment]
dev 分支做了更新

**Comment by magicshui** [comment]
ok，什么时候合并到master?

**Comment by chanxuehong** [comment]
已经合并到了 master 了
